version: '3'
services:
 postgres:
  image: 'postgres:latest'
  environment:
      - POSTGRES_PASSWORD=postgres_password
 api:
  depends_on:
   - postgres
  build:
   dockerfile: Dockerfile
   context: .
  ports:
   - '8080:8080'
  environment:
   - PGUSER=postgres
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPASSWORD=postgres_password
   - PGPORT=5432 